### ISSUE TITLE
Misc UI Cleanup

### ISSUE THREAD

**Issue by kyleboe** [OfficeMomsandDads/scheduler#169] opened 2019-05-01 19:44 UTC
Ensure that spacing is consistent across Mobile/Desktop forms. Create related issues if scope is not small.

**Comment by sarahwicks** [comment] 2019-05-22 21:39
@kyleboe Can you add more detail to this ticket so we can triage? We're not sure what the issue is. Thank you!

**Comment by benjaminwood** [comment] 2019-05-24 17:02
Yeah, this issue is too broad. I think it was a placeholder for @kyleboe to follow up directly. I'm going to close it and we can open issues for specific tasks.

**Closed by benjaminwood** 2019-05-24 17:02 UTC
Labels: bug, good first issue
