### ISSUE TITLE
Offices MISSING from the drop down menu

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#214] opened 2019-05-30 18:11 UTC
While sending a new user invite, I noticed there are only 18 (of 24) offices listed as options in the drop down menu.  HELP!

**Comment by kyleboe** [comment] 2019-05-30 18:49
The list for that dropdown is built from this method: https://github.com/OfficeMomsandDads/scheduler/blob/cbb093468fb5c34945d045d253b01f42243d3eca/app/helpers/application_helper.rb#L18-L20
used here:
https://github.com/OfficeMomsandDads/scheduler/blob/cbb093468fb5c34945d045d253b01f42243d3eca/app/views/devise/invitations/new.html.haml#L24

This means that as long as the offices are properly assigned to your user, they should all show up in that dropdown.

**Comment by kyleboe** [comment] 2019-05-30 18:51
Also, if there is an issue like this that is effecting something in the front end, please include screenshots of the issue with context and expected behavior. That will help us more quickly diagnose the problem.

**Comment by nvick** [comment] 2019-05-30 18:51
Lynnwood was missing from the dropdown menu because the new one was not assigned to you after it was recreated.

**Comment by bencoppock** [comment] 2019-06-22 15:59
@nvick can this be closed then?

**Comment by nvick** [comment] 2019-06-22 17:17
@bencoppock yes, thanks for checking!

**Closed by nvick** 2019-06-22 17:17 UTC
Labels: Priority 1, bug, help wanted
