### ISSUE TITLE
Use Default Language and Remove Null Object Pattern

### ISSUE THREAD

**Issue by kyleboe** [OfficeMomsandDads/scheduler#190] opened 2019-05-08 19:57 UTC
Should default to English.

**Comment by benjaminwood** [comment] 2019-05-24 14:55
The "Null Object Pattern" mentioned in the title is used to *display* a default language if none is selected (when creating a need, for example).

The problem is that this is not useful for reporting as we would have many needs with no language from a database perspective. So, the goal is to actually default to English as if it were selected by the user.

**Comment by benjaminwood** [comment] 2019-10-14 18:18
@martinjaimem as noted on #245, here's what I believe needs to be done here:

1. Make `Need#preferred_language` `optional: false` here:

https://github.com/OfficeMomsandDads/scheduler/blob/7670fb43434a70376abf775a11af69afe7e7617c/app/models/need.rb#L9-L11

2. Write a migration for all existing `Need`'s where `preferred_language_id` is null, setting it to English (lookup the English language to assign the id). Example (pseudo code):

```ruby
english_language = Language.find_by(name: 'English')
needs = Need.where(preferred_language_id: nil)
needs.update_all(preferred_language_id: english_language.id)
```

3. Write a migration to make `Need#preferred_language_id` NOT NULL.

4. In the UI, ensure that the preferred_language dropdown default to English.

5. Remove all references to `NullLanguage`, including the `Need#preferred_language`  method and the `NullLanguage` class itself.

Feel free to ask myself or @nvick if you have question, we composed these specs together.

Thanks for your help!!!

**Comment by FatherofDharma** [comment] 2019-10-30 17:16
These changes have all been made, submitted, and merged. They probably need a final looking over before the issue is closed. Just as a side note, this may also mean looking back at issue #245, to see the impact from these changes.

**Closed** 2019-11-06 16:38 UTC
Labels: Priority 3, enhancement, good first issue, hacktoberfest, small
